name: Build

on:
    push:
        branches:
            - 'main'
            - 'renovate/*'
        tags:
            - 'v*' # For v1.0, v0.1.0, etc
    pull_request:
        branches:
            - 'main'
    schedule:
        -   cron: '0 0 * * *'
    workflow_dispatch:

concurrency:
    group: ${{ format('{0}-{1}', github.job, github.ref) }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            -   name: Create out directory
                run: mkdir -p out

            -   name: Make
                run: make

            -   name: Upload Build Results
                uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
                with:
                    name: Build Results (on ${{ matrix.os }})
                    path: ${{ github.workspace }}/out/